// <auto-generated />
namespace AlarmEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AlarmDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlarmDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201912100734574_AlarmDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
